name: Docker Build & Publish

on:
  push:
    # 触发条件2：推送标签时构建版本镜像
    tags: [ "v*.*.*" ]

env:
  REGISTRY: docker.io
  DOCKER_REPO: alex78218/exiliumgf_bbs  # 固定仓库地址"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 步骤1：检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤2：提取版本号
      - name: Extract version metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{env.DOCKER_REPO}}
          tags: |
            type=raw,value=latest
            type=ref,event=tag

      # 步骤3：登录 Docker 仓库
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 步骤4：构建并推送镜像
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
            windows/amd64